### ISSUE TITLE
2018-08-21: weekly todo list

### ISSUE THREAD

**Issue by VJalili** [CloudVE/mgmt#1]
- [x] Update genomespace to use cloudbridge v.1; [ @nuwang ]
- [x] Cloudbridge v1 release; [@afgane @nuwang ]
- [x] Issue https://github.com/CloudVE/cloudbridge/issues/140 ; [ @afgane  ] 
- [x] `id_label` (https://github.com/CloudVE/cloudbridge/issues/142); [ @nuwang  @almahmoud ]

-  PR the [`upgrade_cloudbridge` branch](https://github.com/vjalili/galaxy/tree/upgrade_cloudbridge) after Cloudbridge v1 is released; [ @vjalili ]
 _Cloudbridge v1 is not released, hence this cannot be implemented._
-  Upgrade the version of the pinned required `keystoneclient` from `==3.10.0` to `>=3.13.0` in Galaxy. @vjalili
_Genomespace is not updated, hence this cannot be implemented._
