### ISSUE TITLE
2018-09-12: weekly todo list

### ISSUE THREAD

**Issue by VJalili** [CloudVE/mgmt#2]
- [x] https://github.com/galaxyproject/galaxy/pull/5903 review and merge; (@VJalili, @afgane)
- [ ] https://github.com/galaxyproject/galaxy/pull/6583 review and merge; (@VJalili, @afgane)
- [x] Updating CloudLaunch for CloudBridge v1 (@afgane)
- [ ] Add Galaxy-Docker-Stable on Azure in CloudLaunch (@almahmoud)
- [x] GVL 4.4/Galaxy 18.05 release (@nuwang)
