### ISSUE TITLE
2018-10-16: Federated Galaxy Weekly Todo List

### ISSUE THREAD

**Issue by VJalili** [CloudVE/mgmt#3]
- [x] rename Galaxy [cloud **download** tool](https://github.com/galaxyproject/galaxy/pull/6583) [@vjalili]
- [x] rename Galaxy cloud **upload** tool [@vjalili] (https://github.com/galaxyproject/galaxy/pull/6899)
- [x] review the https://github.com/galaxyproject/galaxy/pull/6583 PR [@Enis]
- [x] issues reported on sentry.galaxyproject.org: auth issue [@almahmoud]
- [ ] issues reported on sentry.galaxyproject.org: no user profile; [@almahmoud]
