### ISSUE TITLE
2018-10-23: Federated Galaxy Weekly Todo List

### ISSUE THREAD

**Issue by VJalili** [CloudVE/mgmt#4]
- [x] issues reported on sentry.galaxyproject.org: userprofile issue [@almahmoud]
- [x] find a name for the dynamic job runner and make it an independent library available from pypi;
- [ ] make WIP PR for a built-in cloud job runner (related to the previous point);
- [x] phone call with Nate (https://github.com/galaxyproject/galaxy/issues/6139);
- [x] Add timestamp to send job log [@vjalili];
- [x] update https://github.com/galaxyproject/galaxy/pull/6583 according to the discussion with Enis [@vjalili];
- [x] review https://github.com/galaxyproject/galaxy/pull/6583 (@afgane]

stretch goals:
- [ ] Add support for filtering application versions by range (e.g. deployments.list(version__lte=’1.0.0’, version__gte=’0.1.0’)
ref: https://stackoverflow.com/questions/46074662/django-filter-comparison-by-version-string
http://cjlarose.com/2014/01/14/django-custom-field-version-number.html
- [ ] Make cloudlaunch health checks run as a Celery cron job
